- name: Get interfaces config
  hosts: netconf
  tasks:
    - name: netconf get-config
      ansible.netcommon.netconf_get:
        source: running
        display: native
        filter:
          interfaces:
            "@xmlns": "http://openconfig.net/yang/interfaces"
      register: result
    - name: print result data
      ansible.builtin.debug:
        var: result.output.data
