- name: Edit Interfaces
  hosts: netconf
  tasks:
    - name: netconf edit
      ansible.netcommon.netconf_config:
        content: |
            <config xmlns="urn:ietf:params:xml:ns:netconf:base:1.0">
              <interfaces xmlns="http://openconfig.net/yang/interfaces">
                <interface>
                  <name>virt1</name>
                  <config>
                    <name>virt1</name>
                    <type xmlns:ianaift="urn:ietf:params:xml:ns:yang:iana-if-type">ianaift:ethernetCsmacd</type>
                  </config>
                </interface>
              </interfaces>
            </config>
      register: result
